import type { Equipment, MuscleGroup } from '@shark/contracts';

export interface SeedExercise {
  slug: string;
  name: string;
  aliases: string[];
  equipment: Equipment;
  primary: MuscleGroup[];
  secondary: MuscleGroup[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  instructions: string[];
  cues: string[];
  contraindications: string[];
  usesBarbell: boolean;
  isUnilateral: boolean;
  restSec: number;
  stepKg: number;
  subs: string[];
}

/** A working exercise library. Enough breadth that programs, substitutions,
 *  recovery mapping and the equipment QR link all have real data behind them. */
export const EXERCISES: SeedExercise[] = [
  {
    slug: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    aliases: ['Bench', 'Flat bench'],
    equipment: 'barbell',
    primary: ['chest'],
    secondary: ['front_delt', 'triceps'],
    difficulty: 'intermediate',
    instructions: [
      'Set your shoulder blades down and back against the bench.',
      'Take the bar out with straight arms, directly over your shoulders.',
      'Lower to the lower half of your chest, elbows around 45 degrees.',
      'Press back to the start without letting the ribcage flare.',
    ],
    cues: ['Feet planted', 'Bar over mid-chest at the bottom', 'Push yourself away from the bar'],
    contraindications: ['Shoulder impingement', 'Recent pec strain'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 150,
    stepKg: 2.5,
    subs: ['dumbbell-bench-press', 'machine-chest-press', 'push-up'],
  },
  {
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    aliases: ['DB bench'],
    equipment: 'dumbbell',
    primary: ['chest'],
    secondary: ['front_delt', 'triceps'],
    difficulty: 'beginner',
    instructions: ['Start with the dumbbells over your shoulders.', 'Lower until you feel a stretch across the chest.', 'Press up and slightly together.'],
    cues: ['Wrists stacked over elbows', 'Control the bottom'],
    contraindications: ['Shoulder impingement'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2,
    subs: ['barbell-bench-press', 'machine-chest-press'],
  },
  {
    slug: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    aliases: ['Incline DB press'],
    equipment: 'dumbbell',
    primary: ['chest', 'front_delt'],
    secondary: ['triceps'],
    difficulty: 'beginner',
    instructions: ['Set the bench to about 30 degrees.', 'Press from the upper chest to over the shoulders.'],
    cues: ['Do not let the bench go too steep', 'Elbows under the wrists'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2,
    subs: ['incline-barbell-press', 'machine-chest-press'],
  },
  {
    slug: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    aliases: [],
    equipment: 'barbell',
    primary: ['chest', 'front_delt'],
    secondary: ['triceps'],
    difficulty: 'intermediate',
    instructions: ['Set the bench to 30 degrees.', 'Lower to the collarbone, press back over the shoulders.'],
    cues: ['Keep the bar path vertical'],
    contraindications: ['Shoulder impingement'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 150,
    stepKg: 2.5,
    subs: ['incline-dumbbell-press'],
  },
  {
    slug: 'machine-chest-press',
    name: 'Machine Chest Press',
    aliases: ['Chest press'],
    equipment: 'machine',
    primary: ['chest'],
    secondary: ['front_delt', 'triceps'],
    difficulty: 'beginner',
    instructions: ['Set the seat so the handles sit at mid-chest.', 'Press out and control the return.'],
    cues: ['Shoulder blades stay back against the pad'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 5,
    subs: ['dumbbell-bench-press', 'push-up'],
  },
  {
    slug: 'push-up',
    name: 'Push-Up',
    aliases: ['Press-up'],
    equipment: 'bodyweight',
    primary: ['chest'],
    secondary: ['front_delt', 'triceps', 'core'],
    difficulty: 'beginner',
    instructions: ['Hands under the shoulders, body in one line.', 'Lower the chest to just off the floor and press back.'],
    cues: ['Ribs down', 'Squeeze the glutes'],
    contraindications: ['Wrist pain'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['machine-chest-press'],
  },
  {
    slug: 'seated-shoulder-press',
    name: 'Seated Shoulder Press',
    aliases: ['Overhead press', 'OHP'],
    equipment: 'dumbbell',
    primary: ['front_delt'],
    secondary: ['side_delt', 'triceps'],
    difficulty: 'intermediate',
    instructions: ['Sit tall with the dumbbells at shoulder height.', 'Press overhead without arching the lower back.'],
    cues: ['Ribs stacked over hips', 'Full lockout'],
    contraindications: ['Shoulder impingement', 'Lower back pain'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2,
    subs: ['machine-shoulder-press', 'landmine-press'],
  },
  {
    slug: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    aliases: [],
    equipment: 'machine',
    primary: ['front_delt'],
    secondary: ['triceps'],
    difficulty: 'beginner',
    instructions: ['Set the seat so the handles start at ear height.', 'Press overhead and control back down.'],
    cues: ['Do not slam the lockout'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 5,
    subs: ['seated-shoulder-press'],
  },
  {
    slug: 'landmine-press',
    name: 'Landmine Press',
    aliases: [],
    equipment: 'barbell',
    primary: ['front_delt'],
    secondary: ['chest', 'core'],
    difficulty: 'beginner',
    instructions: ['Hold the barbell end at shoulder height.', 'Press up and slightly forward.'],
    cues: ['Good option when overhead is uncomfortable'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 90,
    stepKg: 2.5,
    subs: ['seated-shoulder-press'],
  },
  {
    slug: 'lateral-raise',
    name: 'Lateral Raise',
    aliases: ['Side raise'],
    equipment: 'dumbbell',
    primary: ['side_delt'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Raise the dumbbells out to shoulder height with a slight elbow bend.', 'Lower under control.'],
    cues: ['Lead with the elbows', 'Do not shrug'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['cable-lateral-raise'],
  },
  {
    slug: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    aliases: [],
    equipment: 'cable',
    primary: ['side_delt'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Set the pulley low, raise across the body to shoulder height.'],
    cues: ['Constant tension through the range'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 60,
    stepKg: 2.5,
    subs: ['lateral-raise'],
  },
  {
    slug: 'cable-fly',
    name: 'Cable Fly',
    aliases: ['Pec fly'],
    equipment: 'cable',
    primary: ['chest'],
    secondary: ['front_delt'],
    difficulty: 'beginner',
    instructions: ['Set the pulleys at chest height.', 'Bring the handles together in front of the chest with soft elbows.'],
    cues: ['Think about hugging, not pressing'],
    contraindications: ['Recent pec strain'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 75,
    stepKg: 2.5,
    subs: ['pec-deck'],
  },
  {
    slug: 'pec-deck',
    name: 'Pec Deck',
    aliases: [],
    equipment: 'machine',
    primary: ['chest'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Set the pads at chest height and bring the handles together.'],
    cues: ['Slow on the way out'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 75,
    stepKg: 5,
    subs: ['cable-fly'],
  },
  {
    slug: 'triceps-rope-pushdown',
    name: 'Triceps Rope Pushdown',
    aliases: ['Rope pushdown'],
    equipment: 'cable',
    primary: ['triceps'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Elbows pinned to your sides, press down and spread the rope at the bottom.'],
    cues: ['Elbows stay still'],
    contraindications: ['Elbow tendinopathy'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 2.5,
    subs: ['overhead-triceps-extension', 'dip'],
  },
  {
    slug: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    aliases: [],
    equipment: 'cable',
    primary: ['triceps'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Face away from the pulley, extend the elbows overhead.'],
    cues: ['Keep the ribs down'],
    contraindications: ['Elbow tendinopathy'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 2.5,
    subs: ['triceps-rope-pushdown'],
  },
  {
    slug: 'dip',
    name: 'Dip',
    aliases: ['Parallel bar dip'],
    equipment: 'bodyweight',
    primary: ['triceps', 'chest'],
    secondary: ['front_delt'],
    difficulty: 'intermediate',
    instructions: ['Lower until the upper arms are about parallel to the floor, then press back up.'],
    cues: ['Stay slightly forward for chest, upright for triceps'],
    contraindications: ['Shoulder impingement'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2.5,
    subs: ['triceps-rope-pushdown'],
  },
  {
    slug: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    aliases: ['Back squat', 'Squat'],
    equipment: 'barbell',
    primary: ['quads', 'glutes'],
    secondary: ['lower_back', 'core', 'hamstrings'],
    difficulty: 'intermediate',
    instructions: [
      'Bar on the upper back, feet about shoulder width.',
      'Sit down between your hips, keeping the whole foot loaded.',
      'Stand back up without letting the hips shoot first.',
    ],
    cues: ['Big breath and brace before you go down', 'Knees track over the toes'],
    contraindications: ['Knee pain under load', 'Lower back injury'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 180,
    stepKg: 2.5,
    subs: ['leg-press', 'goblet-squat', 'hack-squat'],
  },
  {
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    aliases: [],
    equipment: 'dumbbell',
    primary: ['quads', 'glutes'],
    secondary: ['core'],
    difficulty: 'beginner',
    instructions: ['Hold a dumbbell at the chest and squat between the hips.'],
    cues: ['Elbows inside the knees at the bottom'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 2,
    subs: ['barbell-back-squat', 'leg-press'],
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    aliases: [],
    equipment: 'machine',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    difficulty: 'beginner',
    instructions: ['Feet mid-platform, lower until the knees reach about 90 degrees, press back.'],
    cues: ['Do not let the lower back round off the pad'],
    contraindications: ['Knee pain under load'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 5,
    subs: ['hack-squat', 'barbell-back-squat'],
  },
  {
    slug: 'hack-squat',
    name: 'Hack Squat',
    aliases: [],
    equipment: 'machine',
    primary: ['quads'],
    secondary: ['glutes'],
    difficulty: 'intermediate',
    instructions: ['Shoulders under the pads, squat to depth and drive back up.'],
    cues: ['Whole foot stays down'],
    contraindications: ['Knee pain under load'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 5,
    subs: ['leg-press'],
  },
  {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    aliases: ['RDL'],
    equipment: 'barbell',
    primary: ['hamstrings', 'glutes'],
    secondary: ['lower_back', 'traps'],
    difficulty: 'intermediate',
    instructions: [
      'Start standing with the bar against your thighs.',
      'Push the hips back, keeping the bar close and the back flat.',
      'Stop where the hamstrings stop stretching, then drive the hips forward.',
    ],
    cues: ['Hips back, not down', 'Bar stays on the legs'],
    contraindications: ['Lower back injury', 'Hamstring strain'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 150,
    stepKg: 2.5,
    subs: ['seated-leg-curl', 'good-morning'],
  },
  {
    slug: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    aliases: ['Deadlift'],
    equipment: 'barbell',
    primary: ['hamstrings', 'glutes', 'lower_back'],
    secondary: ['traps', 'lats', 'forearms'],
    difficulty: 'advanced',
    instructions: ['Bar over mid-foot, take the slack out, then push the floor away.'],
    cues: ['Chest up before the bar moves', 'Lock out with the glutes, not the lower back'],
    contraindications: ['Lower back injury', 'Disc issues'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 210,
    stepKg: 2.5,
    subs: ['romanian-deadlift', 'trap-bar-deadlift'],
  },
  {
    slug: 'trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    aliases: ['Hex bar deadlift'],
    equipment: 'barbell',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'traps'],
    difficulty: 'intermediate',
    instructions: ['Stand inside the bar, sit down into the handles, then stand up.'],
    cues: ['Usually easier on the lower back than a straight bar'],
    contraindications: [],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 180,
    stepKg: 2.5,
    subs: ['conventional-deadlift'],
  },
  {
    slug: 'good-morning',
    name: 'Good Morning',
    aliases: [],
    equipment: 'barbell',
    primary: ['hamstrings'],
    secondary: ['lower_back', 'glutes'],
    difficulty: 'advanced',
    instructions: ['Bar on the upper back, hinge forward with a flat back, return to standing.'],
    cues: ['Start much lighter than you think'],
    contraindications: ['Lower back injury'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2.5,
    subs: ['romanian-deadlift'],
  },
  {
    slug: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    aliases: [],
    equipment: 'machine',
    primary: ['hamstrings'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Curl the pad down and control the return.'],
    cues: ['Do not let the hips lift'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 75,
    stepKg: 5,
    subs: ['romanian-deadlift'],
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    aliases: [],
    equipment: 'machine',
    primary: ['quads'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Extend the knees fully and lower under control.'],
    cues: ['Pause briefly at the top'],
    contraindications: ['Patellar pain'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 75,
    stepKg: 5,
    subs: ['leg-press'],
  },
  {
    slug: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    aliases: [],
    equipment: 'barbell',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    difficulty: 'intermediate',
    instructions: ['Shoulders on the bench, bar across the hips, drive to a flat torso.'],
    cues: ['Tuck the chin', 'Squeeze at the top, do not overarch'],
    contraindications: [],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 120,
    stepKg: 2.5,
    subs: ['glute-bridge'],
  },
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    aliases: [],
    equipment: 'bodyweight',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    difficulty: 'beginner',
    instructions: ['Drive the hips up from the floor and squeeze at the top.'],
    cues: ['Push through the heels'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['hip-thrust'],
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    aliases: ['Rear-foot elevated split squat'],
    equipment: 'dumbbell',
    primary: ['quads', 'glutes'],
    secondary: ['core'],
    difficulty: 'intermediate',
    instructions: ['Rear foot on a bench, lower the back knee towards the floor, drive back up.'],
    cues: ['Stay tall through the torso'],
    contraindications: ['Knee pain under load'],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 120,
    stepKg: 2,
    subs: ['walking-lunge', 'leg-press'],
  },
  {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    aliases: [],
    equipment: 'dumbbell',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'core'],
    difficulty: 'beginner',
    instructions: ['Step forward and lower until both knees are near 90 degrees, then step through.'],
    cues: ['Keep the steps long enough to load the glutes'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 90,
    stepKg: 2,
    subs: ['bulgarian-split-squat'],
  },
  {
    slug: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    aliases: [],
    equipment: 'machine',
    primary: ['calves'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Rise onto the toes fully and lower into a stretch.'],
    cues: ['Pause at both ends'],
    contraindications: ['Achilles tendinopathy'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 5,
    subs: [],
  },
  {
    slug: 'pull-up',
    name: 'Pull-Up',
    aliases: ['Chin-up'],
    equipment: 'bodyweight',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back', 'forearms'],
    difficulty: 'intermediate',
    instructions: ['Hang at full stretch, pull the chest towards the bar, lower fully.'],
    cues: ['Start the pull with the shoulder blades'],
    contraindications: ['Elbow tendinopathy'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 150,
    stepKg: 2.5,
    subs: ['lat-pulldown', 'assisted-pull-up'],
  },
  {
    slug: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    aliases: [],
    equipment: 'machine',
    primary: ['lats'],
    secondary: ['biceps'],
    difficulty: 'beginner',
    instructions: ['Use the machine assistance to complete full-range pull-ups.'],
    cues: ['Reduce the assistance as you get stronger'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 120,
    stepKg: 5,
    subs: ['lat-pulldown'],
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    aliases: [],
    equipment: 'cable',
    primary: ['lats'],
    secondary: ['biceps', 'upper_back'],
    difficulty: 'beginner',
    instructions: ['Pull the bar to the upper chest and control it back up.'],
    cues: ['Do not lean back excessively'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 5,
    subs: ['pull-up'],
  },
  {
    slug: 'barbell-row',
    name: 'Barbell Row',
    aliases: ['Bent-over row'],
    equipment: 'barbell',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'lower_back'],
    difficulty: 'intermediate',
    instructions: ['Hinge to about 45 degrees, row the bar to the lower ribs, lower under control.'],
    cues: ['Back stays flat throughout'],
    contraindications: ['Lower back injury'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 150,
    stepKg: 2.5,
    subs: ['seated-cable-row', 'chest-supported-row'],
  },
  {
    slug: 'chest-supported-row',
    name: 'Chest-Supported Row',
    aliases: [],
    equipment: 'machine',
    primary: ['upper_back'],
    secondary: ['lats', 'biceps'],
    difficulty: 'beginner',
    instructions: ['Chest against the pad, row the handles back and squeeze the shoulder blades.'],
    cues: ['No body English — the pad is there for a reason'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 5,
    subs: ['barbell-row', 'seated-cable-row'],
  },
  {
    slug: 'seated-cable-row',
    name: 'Seated Cable Row',
    aliases: [],
    equipment: 'cable',
    primary: ['upper_back', 'lats'],
    secondary: ['biceps'],
    difficulty: 'beginner',
    instructions: ['Sit tall, row the handle to the navel, control the return.'],
    cues: ['Let the shoulder blades travel'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 5,
    subs: ['barbell-row', 'chest-supported-row'],
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    aliases: [],
    equipment: 'cable',
    primary: ['rear_delt'],
    secondary: ['traps', 'upper_back'],
    difficulty: 'beginner',
    instructions: ['Pull the rope towards the face, separating the hands as you go.'],
    cues: ['High elbows'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 2.5,
    subs: ['rear-delt-fly'],
  },
  {
    slug: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    aliases: ['Reverse fly'],
    equipment: 'dumbbell',
    primary: ['rear_delt'],
    secondary: ['upper_back'],
    difficulty: 'beginner',
    instructions: ['Hinge forward and raise the dumbbells out to the sides.'],
    cues: ['Lead with the elbows, not the hands'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['face-pull'],
  },
  {
    slug: 'barbell-curl',
    name: 'Barbell Curl',
    aliases: [],
    equipment: 'barbell',
    primary: ['biceps'],
    secondary: ['forearms'],
    difficulty: 'beginner',
    instructions: ['Curl the bar without swinging, lower under control.'],
    cues: ['Elbows stay by the ribs'],
    contraindications: ['Elbow tendinopathy'],
    usesBarbell: true,
    isUnilateral: false,
    restSec: 75,
    stepKg: 2.5,
    subs: ['dumbbell-curl', 'cable-curl'],
  },
  {
    slug: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    aliases: [],
    equipment: 'dumbbell',
    primary: ['biceps'],
    secondary: ['forearms'],
    difficulty: 'beginner',
    instructions: ['Curl one or both dumbbells, supinating as you go.'],
    cues: ['Full stretch at the bottom'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 60,
    stepKg: 1,
    subs: ['barbell-curl', 'cable-curl'],
  },
  {
    slug: 'cable-curl',
    name: 'Cable Curl',
    aliases: [],
    equipment: 'cable',
    primary: ['biceps'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Curl from a low pulley with constant tension.'],
    cues: ['Do not let the elbows drift forward'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 2.5,
    subs: ['dumbbell-curl'],
  },
  {
    slug: 'plank',
    name: 'Plank',
    aliases: [],
    equipment: 'bodyweight',
    primary: ['core'],
    secondary: ['front_delt'],
    difficulty: 'beginner',
    instructions: ['Hold a straight line from head to heels on the forearms.'],
    cues: ['Ribs down, glutes on'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['dead-bug'],
  },
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    aliases: [],
    equipment: 'bodyweight',
    primary: ['core'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Lower opposite arm and leg while keeping the lower back flat.'],
    cues: ['Move slowly, breathe out on the way down'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: true,
    restSec: 45,
    stepKg: 1,
    subs: ['plank'],
  },
  {
    slug: 'cable-crunch',
    name: 'Cable Crunch',
    aliases: [],
    equipment: 'cable',
    primary: ['core'],
    secondary: [],
    difficulty: 'beginner',
    instructions: ['Kneel below a high pulley and crunch the ribcage towards the hips.'],
    cues: ['Hips stay still — this is spinal flexion'],
    contraindications: ['Disc issues'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 2.5,
    subs: ['plank'],
  },
  {
    slug: 'farmers-carry',
    name: "Farmer's Carry",
    aliases: [],
    equipment: 'dumbbell',
    primary: ['forearms', 'traps'],
    secondary: ['core'],
    difficulty: 'beginner',
    instructions: ['Carry heavy dumbbells for distance or time, staying tall.'],
    cues: ['Shoulders down, breathe'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 2,
    subs: [],
  },
  {
    slug: 'rowing-machine',
    name: 'Rowing Machine',
    aliases: ['Erg', 'Rower'],
    equipment: 'cardio_machine',
    primary: ['cardio'],
    secondary: ['upper_back', 'quads', 'hamstrings'],
    difficulty: 'beginner',
    instructions: ['Drive with the legs, then the back, then the arms. Reverse on the recovery.'],
    cues: ['Legs–back–arms, arms–back–legs'],
    contraindications: ['Lower back injury'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 1,
    subs: ['assault-bike'],
  },
  {
    slug: 'assault-bike',
    name: 'Assault Bike',
    aliases: ['Air bike'],
    equipment: 'cardio_machine',
    primary: ['cardio'],
    secondary: ['quads'],
    difficulty: 'beginner',
    instructions: ['Push and pull the handles while driving with the legs.'],
    cues: ['Pace it — this one punishes a fast start'],
    contraindications: [],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 90,
    stepKg: 1,
    subs: ['rowing-machine'],
  },
  {
    slug: 'treadmill-intervals',
    name: 'Treadmill Intervals',
    aliases: [],
    equipment: 'cardio_machine',
    primary: ['cardio'],
    secondary: ['calves', 'quads'],
    difficulty: 'beginner',
    instructions: ['Alternate hard efforts with easy recoveries at a set ratio.'],
    cues: ['Straddle the belt to start and stop hard efforts safely'],
    contraindications: ['Achilles tendinopathy'],
    usesBarbell: false,
    isUnilateral: false,
    restSec: 60,
    stepKg: 1,
    subs: ['assault-bike'],
  },
];
