/** Names for the demo gym. Bengaluru-based tenant, so the roster reads like one. */

export const MEMBER_NAMES: Array<[string, string]> = [
  ['Rhea', 'Kapoor'],
  ['Siddharth', 'Venkatesh'],
  ['Nikita', 'Bhat'],
  ['Devraj', 'Rao'],
  ['Meera', 'Joshi'],
  ['Rohit', 'Bhaskar'],
  ['Tanvi', 'Desai'],
  ['Arjun', 'Nair'],
  ['Kavya', 'Reddy'],
  ['Imran', 'Sheikh'],
  ['Priya', 'Iyer'],
  ['Vikram', 'Chawla'],
  ['Ananya', 'Ghosh'],
  ['Karthik', 'Subramanian'],
  ['Sneha', 'Pillai'],
  ['Rahul', 'Mehta'],
  ['Divya', 'Krishnan'],
  ['Farhan', 'Qureshi'],
  ['Lakshmi', 'Menon'],
  ['Aditya', 'Shetty'],
  ['Pooja', 'Agarwal'],
  ['Nikhil', 'Verma'],
  ['Shruti', 'Kulkarni'],
  ['Zoya', 'Ansari'],
  ['Manish', 'Gupta'],
  ['Ishita', 'Banerjee'],
  ['Varun', 'Malhotra'],
  ['Neha', 'Sinha'],
  ['Gaurav', 'Thakur'],
  ['Anjali', 'Prasad'],
  ['Sameer', 'Fernandes'],
  ['Ritika', 'Chandra'],
  ['Yash', 'Patil'],
  ['Aisha', 'Khan'],
  ['Harsh', 'Vora'],
  ['Trisha', 'Dutta'],
  ['Omkar', 'Deshpande'],
  ['Nandini', 'Raghavan'],
];

export const STAFF_SEED = [
  { name: 'Vikas Menon', role: 'owner', email: 'owner@sharkfitness.in', specialties: [] },
  { name: 'Sunita Rao', role: 'branch_manager', email: 'manager@sharkfitness.in', specialties: [] },
  { name: 'Deepa Kumar', role: 'reception', email: 'reception@sharkfitness.in', specialties: [] },
  {
    name: 'Rehan Ahmed',
    role: 'trainer',
    email: 'rehan@sharkfitness.in',
    specialties: ['Strength', 'Hypertrophy', 'Powerlifting'],
  },
  {
    name: 'Nikhil Rao',
    role: 'trainer',
    email: 'nikhil@sharkfitness.in',
    specialties: ['HIIT', 'Conditioning', 'Fat loss'],
  },
  {
    name: 'Priya Sharma',
    role: 'trainer',
    email: 'priya@sharkfitness.in',
    specialties: ['Mobility', 'Beginners', 'Pre/post-natal'],
  },
  {
    name: 'Ravi Kulkarni',
    role: 'accountant',
    email: 'accounts@sharkfitness.in',
    specialties: [],
  },
] as const;

export const CLASS_TYPES = [
  { name: 'Apex HIIT', category: 'cardio', duration: 45, intensity: 'high', desc: 'Interval conditioning in blocks of four.' },
  { name: 'Strength Clinic', category: 'strength', duration: 60, intensity: 'moderate', desc: 'Coached barbell technique in small groups.' },
  { name: 'Open Water Swim', category: 'aquatic', duration: 45, intensity: 'moderate', desc: 'Technique and endurance sets in the pool.' },
  { name: 'Deep Mobility', category: 'mobility', duration: 30, intensity: 'low', desc: 'Hips, thoracic spine and ankles. Bring socks.' },
  { name: 'Spin Sprint', category: 'cardio', duration: 45, intensity: 'high', desc: 'Sprint intervals on the bikes.' },
  { name: 'Reef Yoga', category: 'mind_body', duration: 60, intensity: 'low', desc: 'Slow flow with a long hold at the end.' },
  { name: 'Cage Boxing', category: 'combat', duration: 45, intensity: 'high', desc: 'Pad work and footwork. Gloves provided.' },
  { name: 'Foundations', category: 'strength', duration: 45, intensity: 'low', desc: 'For your first eight weeks in the gym.' },
] as const;

export const RETAIL = [
  { name: 'Shark Whey 1kg — Chocolate', sku: 'SUP-WHY-CH1', category: 'Supplements', price: 249_900, cost: 168_000 },
  { name: 'Shark Whey 1kg — Vanilla', sku: 'SUP-WHY-VA1', category: 'Supplements', price: 249_900, cost: 168_000 },
  { name: 'Creatine Monohydrate 250g', sku: 'SUP-CRE-250', category: 'Supplements', price: 119_900, cost: 72_000 },
  { name: 'Shaker — Depot', sku: 'ACC-SHK-001', category: 'Accessories', price: 39_900, cost: 18_000 },
  { name: 'Lifting Straps', sku: 'ACC-STR-001', category: 'Accessories', price: 89_900, cost: 42_000 },
  { name: 'Knee Sleeves 7mm', sku: 'ACC-KNE-7MM', category: 'Accessories', price: 249_900, cost: 140_000 },
  { name: 'Shark Tee — Black', sku: 'APP-TEE-BLK', category: 'Apparel', price: 129_900, cost: 58_000 },
  { name: 'Electrolyte Sachets (12)', sku: 'SUP-ELE-012', category: 'Supplements', price: 59_900, cost: 31_000 },
  { name: 'Resistance Band Set', sku: 'ACC-BND-SET', category: 'Accessories', price: 149_900, cost: 76_000 },
  { name: 'Cold Brew Coffee 250ml', sku: 'CAF-CLD-250', category: 'Cafe', price: 19_900, cost: 9_000 },
] as const;

export const EQUIPMENT_SEED = [
  { name: 'Rogue Power Rack 1', area: 'Platform', model: 'RML-490C', vendor: 'Rogue', exercise: 'barbell-back-squat' },
  { name: 'Rogue Power Rack 2', area: 'Platform', model: 'RML-490C', vendor: 'Rogue', exercise: 'barbell-back-squat' },
  { name: 'Deadlift Platform A', area: 'Platform', model: 'DL-STD', vendor: 'Rogue', exercise: 'conventional-deadlift' },
  { name: 'Flat Bench 1', area: 'Free weights', model: 'FB-200', vendor: 'Rogue', exercise: 'barbell-bench-press' },
  { name: 'Flat Bench 2', area: 'Free weights', model: 'FB-200', vendor: 'Rogue', exercise: 'barbell-bench-press' },
  { name: 'Adjustable Bench 1', area: 'Free weights', model: 'AB-300', vendor: 'Rogue', exercise: 'incline-dumbbell-press' },
  { name: 'Cable Crossover', area: 'Cable zone', model: 'CX-900', vendor: 'Life Fitness', exercise: 'cable-fly' },
  { name: 'Lat Pulldown', area: 'Cable zone', model: 'LP-500', vendor: 'Life Fitness', exercise: 'lat-pulldown' },
  { name: 'Leg Press 45°', area: 'Machines', model: 'LP-45', vendor: 'Hammer Strength', exercise: 'leg-press' },
  { name: 'Hack Squat', area: 'Machines', model: 'HS-200', vendor: 'Hammer Strength', exercise: 'hack-squat' },
  { name: 'Seated Leg Curl', area: 'Machines', model: 'SLC-100', vendor: 'Technogym', exercise: 'seated-leg-curl' },
  { name: 'Chest Press Machine', area: 'Machines', model: 'CP-400', vendor: 'Technogym', exercise: 'machine-chest-press' },
  { name: 'Concept2 Rower 1', area: 'Cardio', model: 'RowErg', vendor: 'Concept2', exercise: 'rowing-machine' },
  { name: 'Concept2 Rower 2', area: 'Cardio', model: 'RowErg', vendor: 'Concept2', exercise: 'rowing-machine' },
  { name: 'Assault Bike 1', area: 'Cardio', model: 'AirBike Classic', vendor: 'Assault', exercise: 'assault-bike' },
  { name: 'Treadmill 3', area: 'Cardio', model: 'Run Artis', vendor: 'Technogym', exercise: 'treadmill-intervals' },
] as const;

export const MEDIA_SEED = [
  { title: 'Deep Water Conditioning', category: 'Conditioning', trainer: 'Nikhil Rao', min: 32, level: 'intermediate' },
  { title: 'Bench Press Setup, Properly', category: 'Technique', trainer: 'Rehan Ahmed', min: 14, level: 'beginner' },
  { title: 'Hip Mobility for Squatters', category: 'Mobility', trainer: 'Priya Sharma', min: 22, level: 'beginner' },
  { title: 'Reef Flow — Evening Yoga', category: 'Mind & body', trainer: 'Priya Sharma', min: 45, level: 'beginner' },
  { title: 'Twenty Minute Full Body', category: 'Strength', trainer: 'Rehan Ahmed', min: 20, level: 'intermediate' },
  { title: 'Rowing Technique Clinic', category: 'Technique', trainer: 'Nikhil Rao', min: 18, level: 'beginner' },
  { title: 'Deadlift: Bracing and Setup', category: 'Technique', trainer: 'Rehan Ahmed', min: 16, level: 'advanced' },
  { title: 'Ten Minute Cool Down', category: 'Recovery', trainer: 'Priya Sharma', min: 10, level: 'beginner' },
] as const;

export const ACHIEVEMENTS_SEED = [
  { code: 'first_session', name: 'First Dive', description: 'Log your first session', tier: 'bronze' },
  { code: 'ten_sessions', name: 'Ten Deep', description: 'Log ten sessions', tier: 'bronze' },
  { code: 'fifty_sessions', name: 'Fifty Fathoms', description: 'Log fifty sessions', tier: 'silver' },
  { code: 'hundred_sessions', name: 'Century', description: 'Log a hundred sessions', tier: 'gold' },
  { code: 'first_pr', name: 'New Ground', description: 'Set your first personal record', tier: 'bronze' },
  { code: 'four_week_streak', name: 'Tide Turner', description: 'Hit your weekly target four weeks running', tier: 'silver' },
  { code: 'class_regular', name: 'Pack Animal', description: 'Attend twenty classes', tier: 'silver' },
  { code: 'habit_month', name: 'Steady Current', description: 'Keep a habit for thirty days', tier: 'gold' },
  { code: 'first_referral', name: 'Recruiter', description: 'Refer a friend who joins', tier: 'bronze' },
  { code: 'early_bird', name: 'Dawn Patrol', description: 'Twenty sessions before 7am', tier: 'silver' },
] as const;
